# Generated by Django 5.2.16 on 2026-07-29 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('logger_name', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_method', models.CharField(blank=True, default='', max_length=16)),
                ('request_path', models.CharField(blank=True, default='', max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('duration_ms', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('pathname', models.CharField(blank=True, default='', max_length=512)),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('function_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('thread_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('exception_text', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'level'], name='logs_logent_created_9ed039_idx'), models.Index(fields=['logger_name', 'created_at'], name='logs_logent_logger__edefa0_idx'), models.Index(fields=['request_path', 'created_at'], name='logs_logent_request_defae5_idx')],
            },
        ),
    ]
