# Generated by Django 5.2.16 on 2026-07-29 07:29

import apps.accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('banner', models.ImageField(blank=True, null=True, storage=apps.accounts.storage.SupabaseStorage(), upload_to='communities/banners/')),
                ('icon', models.ImageField(blank=True, null=True, storage=apps.accounts.storage.SupabaseStorage(), upload_to='communities/icons/')),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], db_index=True, default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-joined_at',),
                'unique_together': {('community', 'user')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', through='communities.CommunityMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
