# Generated by Django 5.2.16 on 2026-07-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('channel_type', models.CharField(choices=[('announcements', 'Announcements'), ('general', 'General'), ('projects', 'Projects'), ('resources', 'Resources'), ('events', 'Events'), ('doubts', 'Doubts'), ('random', 'Random')], db_index=True, default='general', max_length=30)),
                ('permission_type', models.CharField(choices=[('read_only', 'Read Only'), ('write', 'Write'), ('moderator_only', 'Moderator Only')], db_index=True, default='write', max_length=30)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='communities.community')),
            ],
            options={
                'ordering': ('-is_pinned', 'order', 'created_at'),
                'unique_together': {('community', 'slug')},
            },
        ),
    ]
