# Generated by Django 5.2.16 on 2026-07-29 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__username',),
            },
        ),
    ]
