# Generated by Django 5.2.16 on 2026-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_achievements_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_author',
            field=models.BooleanField(default=False),
        ),
    ]
